plugins {
    id 'fabric-loom' version '1.10-SNAPSHOT'
    id 'maven-publish'
}

repositories {
    maven { url = 'https://maven.terraformersmc.com/releases/' }
    mavenLocal()
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings "net.fabricmc:yarn:${project.mappings_version}:v2"
    modImplementation "net.fabricmc:fabric-loader:${project.fabric_loader_version}"
    implementation "com.google.code.findbugs:jsr305:3.0.2"

    include(modApi(fabricApi.module("fabric-api-base", project.fabric_api_version)))
    include(modApi(fabricApi.module("fabric-networking-api-v1", project.fabric_api_version)))
    include(modApi(fabricApi.module("fabric-resource-loader-v0", project.fabric_api_version)))

    def localMalilib = file("../malilib/build/devlibs/malilib-fabric-${project.minecraft_version_out}-${project.malilib_version}-dev.jar")
    def localLitematica = file("../litematica/build/devlibs/litematica-fabric-${project.minecraft_version_out}-${project.litematica_version}-dev.jar")

    if (localMalilib.isFile() && localLitematica.isFile())
    {
        modImplementation files(localMalilib, localLitematica)
    }
    else
    {
        modImplementation "fi.dy.masa.malilib:malilib-fabric-${project.minecraft_version_out}:${project.malilib_version}"
        modImplementation "fi.dy.masa.litematica:litematica-fabric-${project.minecraft_version_out}:${project.litematica_version}"
    }

    modCompileOnly "com.terraformersmc:modmenu:${project.mod_menu_version}"
}

configurations.configureEach {
    resolutionStrategy {
        force("net.fabricmc:fabric-loader:${project.fabric_loader_version}")
    }
}

sourceCompatibility = JavaVersion.VERSION_1_8
targetCompatibility = JavaVersion.VERSION_1_8

group = project.group + '.' + project.mod_id
version = project.mod_version

base {
    archivesName = project.mod_file_name + '-' + project.minecraft_version_out
}

processResources {
    inputs.property 'mod_version', project.mod_version
    filesMatching('fabric.mod.json') {
        expand 'mod_version': project.mod_version
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release = 8
}

tasks.withType(AbstractArchiveTask).configureEach {
    preserveFileTimestamps = true
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            artifactId = base.archivesName.get()
            from components.java
        }
    }
}
