org.gradle.jvmargs = -Xmx3G
org.gradle.daemon = false
org.gradle.cache.cleanup = false

group = dev.froyln
mod_id = schematicpreview
mod_name = SchematicPreview
mod_file_name = schematicpreview-fabric
mod_version = 1.0.0-1.15.2-dev

litematica_version = 0.9.1-1.15.2-dev+xiej.8
malilib_version = 0.18.4+xiej.0

minecraft_version_out = 1.15.2
minecraft_version = 1.15.2
mappings_version = 1.15.2+build.17
fabric_loader_version = 0.16.14
mod_menu_version = 1.10.7
fabric_api_version = 0.28.5+1.15
