package dev.froyln.schematicpreview.gui;

import malilib.gui.icon.BaseIcon;
import malilib.util.data.Identifier;

import dev.froyln.schematicpreview.Reference;

/**
 * Icons for the overlay/toolbar buttons, from {@code textures/gui/icons.png} (generated by
 * {@code tools/gen-icons.py}, own drawings). Each is 12x12 with malilib's three variants side
 * by side: disabled, normal, hovered.
 */
public final class SchematicPreviewIcons
{
    private static final Identifier TEXTURE = new Identifier(Reference.MOD_ID, "textures/gui/icons.png");
    private static final int SIZE = 12;

    public static final BaseIcon FULLSCREEN   = icon(0);
    public static final BaseIcon FREECAM      = icon(1);
    public static final BaseIcon SAVE         = icon(2);
    public static final BaseIcon COPY         = icon(3);
    public static final BaseIcon PREVIEW_TYPE = icon(4);

    private SchematicPreviewIcons()
    {
    }

    private static BaseIcon icon(int row)
    {
        return new BaseIcon(0, row * SIZE, SIZE, SIZE, SIZE, 0, 64, 64, TEXTURE);
    }
}
